name: Auto VPN Subscription

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build-subscription:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build subscriptions
        run: |
          mkdir -p output

          rm -f all.txt clean.txt

          echo "Downloading sources..."

          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_universal.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt" >> all.txt
          echo "" >> all.txt

          echo "Downloading aggregator..."

          curl -L "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt" -o base64.txt

          cat base64.txt | base64 -d >> all.txt || true

          echo "Filtering and removing duplicates..."

          grep -E "^(vless|trojan|hy2|hysteria2|hysteria)://" all.txt | sort -u > clean.txt

          echo "Creating files..."

          grep "^vless://" clean.txt > output/vless.txt || true

          grep "^trojan://" clean.txt > output/trojan.txt || true

          grep -E "^(hy2|hysteria2|hysteria)://" clean.txt > output/hysteria.txt || true

          echo "Done"

          echo "VLESS:"
          wc -l output/vless.txt || true

          echo "TROJAN:"
          wc -l output/trojan.txt || true

          echo "HYSTERIA:"
          wc -l output/hysteria.txt || true

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output/

          git commit -m "Auto update subscriptions" || exit 0

          git push
