name: Auto VPN Subscription

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build-subscription:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build subscription
        run: |
          mkdir -p output
          rm -f all.txt decoded.txt clean.txt

          echo "Downloading sources..."

          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_universal.txt" >> all.txt
          echo "" >> all.txt

          curl -L "https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt" >> all.txt
          echo "" >> all.txt

          echo "Downloading aggregator..."

          curl -L "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt" -o base64.txt

          cat base64.txt | base64 -d >> all.txt || true

          echo "Filtering protocols..."

          grep -E "^(vless|hy2|hysteria2|hysteria)://" all.txt > clean.txt || true

          echo "Removing duplicates..."

          sort -u clean.txt > output/subscription.txt

          echo "Total nodes:"
          wc -l output/subscription.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output/subscription.txt

          git commit -m "Auto update subscription" || exit 0

          git push
